spring: 
  datasource: 
    url: "jdbc:postgresql://localhost:5433/db_ebn_user"
    username: postgres
    password: 123456
  flyway: 
    baseline-on-migrate: true
    enabled: true
  jpa: 
    hibernate.ddl-auto: none
    properties.javax.persistence.schema-generation.create-source: metadata 
    properties.javax.persistence.schema-generation.scripts.action: create
    properties.javax.persistence.schema-generation.scripts.create-target: ebn-user/src/main/resources/db/schema-generation/create_table_tb_user.sql
