spring: 
  datasource: 
    url: "jdbc:postgresql://ebn-worker-pg12:5432/db_ebn_worker"
    username: postgres
    password: 123456
  flyway: 
    baseline-on-migrate: true
    enabled: true
  jpa: 
    hibernate.ddl-auto: none
    properties.hibernate.jdbc.lob.non_contextual_creation: true
