spring: 
  datasource: 
    url: "jdbc:postgresql://localhost:5432/db_ebn_worker"
    username: postgres
    password: 123456
  flyway: 
    baseline-on-migrate: true
    enabled: true
  jpa: 
    hibernate.ddl-auto: none
    properties.javax.persistence.schema-generation.create-source: metadata 
    properties.javax.persistence.schema-generation.scripts.action: create
    properties.javax.persistence.schema-generation.scripts.create-target: ebn-worker/src/main/resources/db/schema-generation/create_table_tb_worker.sql
